name: Run Databricks Job

on:
  push:
    branches: [main]

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI v1.x
        run: |
          pip install databricks-cli --upgrade

      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Trigger Databricks Job
        run: |
          RUN_ID=$(databricks jobs run-now --job-id ${{ secrets.DATABRICKS_JOB_ID }} | jq -r '.run_id')
          echo "Triggered run ID: $RUN_ID"

          # Wait until the job finishes
          while true; do
            STATE=$(databricks runs get --run-id $RUN_ID | jq -r '.state.life_cycle_state')
            RESULT=$(databricks runs get --run-id $RUN_ID | jq -r '.state.result_state')
            echo "Job state: $STATE"
            if [ "$STATE" == "TERMINATED" ]; then
              echo "Job finished with result: $RESULT"
              if [ "$RESULT" != "SUCCESS" ]; then exit 1; fi
              break
            fi
            sleep 20
          done

      - name: Download Deequ Report from DBFS
        run: |
          databricks fs cp -r dbfs:/FileStore/shared_uploads/traininguser8@sudosu.ai/deequ_reports ./deequ_reports

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deequ-report
          path: ./deequ_reports
